version: '2'
services:

  auth:
    image: registry.jincor.com/backend/auth:latest
    build:
        context: ./
        dockerfile: Dockerfile.prod
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
